# Site settings
source: www
title: Recipes
email: recipes@doismellburning.co.uk
description: "Recipes collected by doismellburning"
baseurl: ""
url: "http://recipes.doismellburning.co.uk"

# Build settings
markdown: kramdown
permalink: pretty

collections:
    main_meals:
        output: true
    side_dishes:
        output: true
    desserts:
        output: true
    misc:
        output: true
