# Site settings
title: Recipes
email: recipes@doismellburning.co.uk
description: "Recipes collected by doismellburning"
baseurl: ""
url: "http://recipes.doismellburning.co.uk"

# Build settings
markdown: kramdown
permalink: pretty
